"""Finite-sum rewriting for mmj2 worksheets: `fsumadd`, `fsumle`,
`fsummulc2`, `fsumsplit`, `fsump1`, `fsumss`, `fsumcom`, `fsumdvdsmul`,
`fsumabs`, `fsumdivc`, `fsumshft`, `fsumless`, `fsumf1o`, `fsumxp`,
`fsumrev`, `fprodf1o` and `fprodsplit`
with the bound-variable hygiene of M2-HANDOFF.md built in (the bound variable
must not occur in the antecedent, the range, or a constant factor; violations
raise FSumError before any step is written).

A closure this module cannot derive is supplied from outside in either of two
ways.  `body=` takes the finished body facts as plain worksheet step names --
a step, a list in the order the method needs them, or a dict keyed by the
body text -- and lifts each to the body's antecedent if it is proved further
up, so a caller who already has `( ( ante /\\ k e. A ) -> B e. CC )`, or has
it two levels up, passes it and the Closure is not consulted.  Failing that,
`f.child(k, A)` is the memoized child closure under `( ante /\\ k e. A )` and
`f.have(k, A, E, kind, step)` records one subterm fact on it before the sum
method that needs it runs.  The `prove` argument of `le`, and the `zero` and
`prod` arguments, likewise accept a plain step name.

    from tm import W
    from cl import Closure
    from fsum import FSum
    w = W('label', 'description'); ante = 'N e. NN'
    c = Closure(w, ante, {'N': ('NN', w.s([], 'id', '( N e. NN -> N e. NN )'))})
    f = FSum(w, c)
    f.add('k', '( 1 ... N )', 'k', '1')
        # ( ante -> sum_ k e. ( 1 ... N ) ( k + 1 ) = ( sum_ k e. ( 1 ... N ) k + sum_ k e. ( 1 ... N ) 1 ) )
    f.le('k', '( 1 ... N )', 'k', '( 2 x. k )', lambda child: linarith(w, child.ante, [child.ge0('k')], 'k <_ ( 2 x. k )', closure=child))
        # ( ante -> sum_ k e. ( 1 ... N ) k <_ sum_ k e. ( 1 ... N ) ( 2 x. k ) )
    f.mulc2('k', '( 1 ... N )', 'C', 'k')
        # ( ante -> ( C x. sum_ k e. ( 1 ... N ) k ) = sum_ k e. ( 1 ... N ) ( C x. k ) )
    f.split('k', U, A, B, C, disj, union)
        # ( ante -> sum_ k e. U C = ( sum_ k e. A C + sum_ k e. B C ) ), given the
        # steps disj: ( ante -> ( A i^i B ) = (/) ) and union: ( ante -> U = ( A u. B ) )
    f.ss(k, A, B, C, sub, zero)
        # ( ante -> sum_ k e. A C = sum_ k e. B C ), given sub: A C_ B and
        #   zero: ( ( ante /\\ k e. ( B \\ A ) ) -> C = 0 ) (a step or a callable)
    f.com(j, A, k, B, C)
        # ( ante -> sum_ j e. A sum_ k e. B C = sum_ k e. B sum_ j e. A C )
    f.abs(k, A, B)
        # ( ante -> ( abs ` sum_ k e. A B ) <_ sum_ k e. A ( abs ` B ) )
    f.divc(k, A, C, B)
        # ( ante -> ( sum_ k e. A B / C ) = sum_ k e. A ( B / C ) )
    f.shft(j, M, N, K, A, k)
        # ( ante -> sum_ j e. ( M ... N ) A = sum_ k e. ( ( M + K ) ... ( N + K ) ) B )
    f.prodsplit(k, U, A, B, C, disj, union)
        # ( ante -> prod_ k e. U C = ( prod_ k e. A C x. prod_ k e. B C ) )
    f.less(k, A, C, B, sub)
        # ( ante -> sum_ k e. C B <_ sum_ k e. A B ), given sub: ( ante -> C C_ A )
        #   and a nonnegative real body on A
    f.f1o(k, A, B, n, C, F, G, bij, val)
        # ( ante -> sum_ k e. A B = sum_ n e. C D ), D the body at k := G,
        #   given bij: F : C -1-1-onto-> A and val: ( ( ante /\\ n e. C ) -> ( F ` n ) = G )
    f.xp(j, A, k, B, C, z)
        # ( ante -> sum_ j e. A sum_ k e. B C = sum_ z e. ( A X. B ) D )
    f.rev(j, M, N, K, A, k)
        # ( ante -> sum_ j e. ( M ... N ) A = sum_ k e. ( ( K - N ) ... ( K - M ) ) B )
    f.dvdsmul(M, N, mst, nst, gcd1, j, k, i, A, B, C, prod)
        # ( ante -> ( sum_ j e. X A x. sum_ k e. Y B ) = sum_ i e. Z C ) for the
        #   divisor sets of M, N and ( M x. N )
    f.p1('k', '1', 'N', '( k ^ 2 )')
        # ( ante -> sum_ k e. ( 1 ... ( N + 1 ) ) ( k ^ 2 ) = ( sum_ k e. ( 1 ... N ) ( k ^ 2 ) + ( ( N + 1 ) ^ 2 ) ) )
        # the substitution hypothesis ( k = ( N + 1 ) -> A = B ) is generated by
        # tools/congr.py; N e. ( ZZ>= ` M ) is derived for M = 1 (N e. NN) and
        # M = 0 (N e. NN0), or passed as uz=step

Each method returns the name of the step it adds (name='qed' writes the
qed line).  The closure of the bodies comes from the child closure
`Closure.child(k, A)` of the Closure given at construction.
"""
import os, re, sys
sys.path.insert(0, os.path.dirname(__file__))
from cl import Closure, ClosureError, lift
from congr import congruence, StepGen


class FSumError(Exception):
    pass


def occurs(k, text):
    return re.search(r'(^|\s)%s(\s|$)' % re.escape(k), text) is not None


def SUM(k, A, B):
    return 'sum_ %s e. %s %s' % (k, A, B)


def PROD(k, A, B):
    return 'prod_ %s e. %s %s' % (k, A, B)


def _text(s):
    """the substituted body as tools/congr.py returns it.  `' '.join` over the
    string is the spelling the worksheets of `p1` and `dvdsmul` carry, and it
    preserves the token sequence exactly when every token is one character; it
    would split a token such as `x.`, so the string is taken as it stands
    whenever the two token sequences differ."""
    spread = ' '.join(s)
    return spread if spread.split() == s.split() else s


class FSum:
    def __init__(self, w, closure):
        self.w = w; self.cl = closure; self.ante = closure.ante
        self._children = {}
        self.body = None        # the substituted body the last method computed

    # -- external closure escape ------------------------------------------
    def child(self, k, A):
        """the child closure under ( ante /\\ k e. A ), memoized: a caller
        records a closure step this module cannot derive with
        `f.child(k, A).have(E, kind, step)` before calling the sum method"""
        key = (k, A)
        if key not in self._children:
            self._children[key] = self.cl.child(k, A)
        return self._children[key]

    def have(self, k, A, E, kind, step):
        """record an external closure fact for the body of a sum over k e. A"""
        return self.child(k, A).have(E, kind, step)

    # -- body closures from plain step names -------------------------------
    def _lift(self, step, ante):
        """the step, lifted to ANTE when it is proved under a conjunct of it"""
        try:
            return lift(self.w, step, ante)
        except (ClosureError, KeyError):
            return step

    def _given(self, body, E, kind, idx):
        """the caller's step for the IDX-th body fact, or None.  `body` is a
        step name (the first fact only), a list in the order the method needs
        them, or a dict keyed by the body text or by (text, kind)."""
        if body is None:
            return None
        if isinstance(body, dict):
            return body.get((E, kind)) or body.get(E)
        if isinstance(body, (list, tuple)):
            return body[idx] if idx < len(body) else None
        return body if idx == 0 else None

    def _bcl(self, ch, E, kind, body=None, idx=0):
        """the step proving the body fact under the child antecedent: the
        caller's, lifted if it is proved further up, or the closure's"""
        st = self._given(body, E, kind, idx)
        if st is None:
            return ch.prove(E, kind)
        return self._lift(st, ch.ante)

    def _hyg(self, k, *texts):
        if occurs(k, self.ante):
            raise FSumError('bound variable %s occurs in the antecedent %s' % (k, self.ante))
        for t in texts:
            if occurs(k, t):
                raise FSumError('bound variable %s occurs in %s (a $d violation)' % (k, t))

    def _substh(self, E, sub, leafref='id', prefix='g', spread=False):
        """the substitution hypothesis of a re-indexing lemma and the
        substituted expression: `sub` is {index: replacement}, the antecedent is
        the conjunction of the equations, and tools/congr.py writes the
        congruence.  Returns (step proving ( eq -> E = E' ), E')."""
        w = self.w
        eqs = ['%s = %s' % (v, r) for v, r in sub.items()]
        eq = eqs[0] if len(eqs) == 1 else '( %s )' % ' /\\ '.join(eqs)
        gen = StepGen(prefix)
        if len(eqs) == 1:
            leaves = {list(sub)[0]: w.s([], leafref, '( %s -> %s )' % (eq, eqs[0]))}
        else:
            refs = ['simpl', 'simpr'] if len(eqs) == 2 else ['simp1', 'simp2', 'simp3']
            leaves = dict((v, w.s([], refs[i], '( %s -> %s )' % (eq, eqs[i])))
                          for i, v in enumerate(sub))
        st, new = congruence(E, dict(sub), eq, leaves, gen)
        w.lines.extend(gen.lines)
        if spread:
            new = _text(new)
        if st is None:
            st = w.s([], 'eqidd', '( %s -> %s = %s )' % (eq, E, new))
        return st, new

    def _dv(self, ref, sub):
        """check the distinct-variable conditions of REF against the texts this
        call substitutes into it (tools/dv.py), and raise before any step is
        written.  This is the general form of `_hyg`: the conditions come from
        the database rather than from a rule written here."""
        try:
            import dv as _dv_mod
        except ImportError:
            return
        try:
            bad = _dv_mod.check(ref, sub)
        except Exception:
            return
        if bad:
            raise FSumError('\n'.join(bad))

    def _emit(self, hyps, ref, formula, name):
        f = '( %s -> %s )' % (self.ante, formula)
        if name == 'qed':
            self.w.qed(hyps, ref, f); return 'qed'
        return self.w.s(hyps, ref, f, name=name)

    def add(self, k, A, B, C, name=None, body=None):
        self._hyg(k, A)
        fin = self.cl.mem(A, 'Fin'); ch = self.child(k, A)
        b = self._bcl(ch, B, 'CC', body, 0); c = self._bcl(ch, C, 'CC', body, 1)
        return self._emit([fin, b, c], 'fsumadd', '%s = ( %s + %s )' % (SUM(k, A, '( %s + %s )' % (B, C)), SUM(k, A, B), SUM(k, A, C)), name)

    def le(self, k, A, B, C, prove, name=None, body=None):
        """prove(child) returns the step proving ( ( ante /\\ k e. A ) -> B <_ C );
        it may also be the name of a step already proving it"""
        self._hyg(k, A)
        fin = self.cl.mem(A, 'Fin'); ch = self.child(k, A)
        b = self._bcl(ch, B, 'RR', body, 0); c = self._bcl(ch, C, 'RR', body, 1)
        le = prove(ch) if callable(prove) else self._lift(prove, ch.ante)
        return self._emit([fin, b, c, le], 'fsumle', '%s <_ %s' % (SUM(k, A, B), SUM(k, A, C)), name)

    def mulc2(self, k, A, C, B, name=None, body=None):
        self._hyg(k, A, C)
        fin = self.cl.mem(A, 'Fin'); cc = self.cl.mem(C, 'CC'); ch = self.child(k, A)
        b = self._bcl(ch, B, 'CC', body, 0)
        return self._emit([fin, cc, b], 'fsummulc2', '( %s x. %s ) = %s' % (C, SUM(k, A, B), SUM(k, A, '( %s x. %s )' % (C, B))), name)

    def split(self, k, U, A, B, C, disj, union, name=None, body=None):
        self._hyg(k, U, A, B)
        fin = self.cl.mem(U, 'Fin'); ch = self.child(k, U)
        c = self._bcl(ch, C, 'CC', body, 0)
        return self._emit([disj, union, fin, c], 'fsumsplit', '%s = ( %s + %s )' % (SUM(k, U, C), SUM(k, A, C), SUM(k, B, C)), name)

    def p1(self, k, M, N, A, uz=None, name=None, body=None):
        self._hyg(k, M, N)
        w = self.w
        if uz is None:
            if M == '1':
                i = w.inst('elnnuz'); uz = w.s([self.cl.mem(N, 'NN'), i], 'sylib', '( %s -> %s e. ( ZZ>= ` 1 ) )' % (self.ante, N))
            elif M == '0':
                i = w.inst('elnn0uz'); uz = w.s([self.cl.mem(N, 'NN0'), i], 'sylib', '( %s -> %s e. ( ZZ>= ` 0 ) )' % (self.ante, N))
            else:
                raise FSumError('p1: pass uz, a step proving ( ante -> %s e. ( ZZ>= ` %s ) )' % (N, M))
        rng = '( %s ... ( %s + 1 ) )' % (M, N)
        ch = self.child(k, rng)
        a = self._bcl(ch, A, 'CC', body, 0)
        # the substitution hypothesis ( k = ( N + 1 ) -> A = B )
        st, B = self._substh(A, {k: '( %s + 1 )' % N}, spread=True)
        return self._emit([uz, a, st], 'fsump1', '%s = ( %s + %s )' % (SUM(k, rng, A), SUM(k, '( %s ... %s )' % (M, N), A), B), name)

    # -- wrappers ---------------------------------------------------------
    def pair_child(self, j, A, k, B):
        """the closure under ( ante /\\ ( j e. A /\\ k e. B ) ), memoized"""
        key = (j, A, k, B)
        if key not in self._children:
            self._children[key] = self.cl.pair_child(j, A, k, B)
        return self._children[key]

    def ss(self, k, A, B, C, sub, zero, name=None, body=None):
        """sum_ k e. A C = sum_ k e. B C, from `sub` proving ( ante -> A C_ B )
        and `zero` proving ( ( ante /\\ k e. ( B \\ A ) ) -> C = 0 ); `zero` may
        be a step name or a callable taking the child closure over B \\ A."""
        self._hyg(k, A, B)
        fin = self.cl.mem(B, 'Fin')
        c = self._bcl(self.child(k, A), C, 'CC', body, 0)
        chd = self.child(k, '( %s \\ %s )' % (B, A))
        z = zero(chd) if callable(zero) else self._lift(zero, chd.ante)
        return self._emit([sub, c, z, fin], 'fsumss',
                          '%s = %s' % (SUM(k, A, C), SUM(k, B, C)), name)

    def com(self, j, A, k, B, C, name=None, body=None):
        """sum_ j e. A sum_ k e. B C = sum_ k e. B sum_ j e. A C"""
        if j == k:
            raise FSumError('the two indices must be distinct: %s, %s' % (j, k))
        self._hyg(j, A, B); self._hyg(k, A, B)
        fa = self.cl.mem(A, 'Fin'); fb = self.cl.mem(B, 'Fin')
        c = self._bcl(self.pair_child(j, A, k, B), C, 'CC', body, 0)
        return self._emit([fa, fb, c], 'fsumcom',
                          '%s = %s' % (SUM(j, A, SUM(k, B, C)), SUM(k, B, SUM(j, A, C))), name)

    def abs(self, k, A, B, name=None, body=None):
        """( abs ` sum_ k e. A B ) <_ sum_ k e. A ( abs ` B )"""
        self._hyg(k, A)
        fin = self.cl.mem(A, 'Fin')
        b = self._bcl(self.child(k, A), B, 'CC', body, 0)
        return self._emit([fin, b], 'fsumabs',
                          '( abs ` %s ) <_ %s' % (SUM(k, A, B), SUM(k, A, '( abs ` %s )' % B)), name)

    def divc(self, k, A, C, B, name=None, body=None):
        """( sum_ k e. A B / C ) = sum_ k e. A ( B / C )"""
        self._hyg(k, A, C)
        fin = self.cl.mem(A, 'Fin'); cc = self.cl.mem(C, 'CC')
        b = self._bcl(self.child(k, A), B, 'CC', body, 0)
        ne = self.cl.ne0(C)
        return self._emit([fin, cc, b, ne], 'fsumdivc',
                          '( %s / %s ) = %s' % (SUM(k, A, B), C, SUM(k, A, '( %s / %s )' % (B, C))), name)

    def shft(self, j, M, N, K, A, k, name=None, body=None):
        """sum_ j e. ( M ... N ) A = sum_ k e. ( ( M + K ) ... ( N + K ) ) B,
        where B is A with j replaced by ( k - K ) (tools/congr.py writes the
        substitution hypothesis and computes B)"""
        if j == k:
            raise FSumError('the two indices must be distinct: %s, %s' % (j, k))
        self._hyg(j, M, N, K); self._hyg(k, M, N, K)
        w = self.w
        kz, mz, nz = self.cl.mem(K, 'ZZ'), self.cl.mem(M, 'ZZ'), self.cl.mem(N, 'ZZ')
        rng = '( %s ... %s )' % (M, N)
        a = self._bcl(self.child(j, rng), A, 'CC', body, 0)
        st, B = self._substh(A, {j: '( %s - %s )' % (k, K)}, prefix='q')
        rng2 = '( ( %s + %s ) ... ( %s + %s ) )' % (M, K, N, K)
        return self._emit([kz, mz, nz, a, st], 'fsumshft',
                          '%s = %s' % (SUM(j, rng, A), SUM(k, rng2, B)), name)

    def less(self, k, A, C, B, sub, name=None, body=None):
        """sum_ k e. C B <_ sum_ k e. A B: a shorter sum of nonnegative terms is
        smaller.  `sub` proves ( ante -> C C_ A ); the body's realness and
        nonnegativity are taken on the larger range A."""
        self._dv('fsumless', {'k': k, 'ph': self.ante, 'A': A, 'B': B, 'C': C})
        self._hyg(k, A, C)
        fin = self.cl.mem(A, 'Fin'); ch = self.child(k, A)
        b = self._bcl(ch, B, 'RR', body, 0)
        z = self._bcl(ch, B, 'ge0', body, 1)
        return self._emit([fin, b, z, sub], 'fsumless',
                          '%s <_ %s' % (SUM(k, C, B), SUM(k, A, B)), name)

    def f1o(self, k, A, B, n, C, F, G, bij, val, fin=None, name=None, body=None,
            prod=False):
        """sum_ k e. A B = sum_ n e. C D: re-index by a bijection.
        `bij` proves ( ante -> F : C -1-1-onto-> A ), `val` proves
        ( ( ante /\\ n e. C ) -> ( F ` n ) = G ), and `fin` proves
        ( ante -> C e. Fin ) (the closure supplies it when it is not given).
        D is B with the index k replaced by G, written by tools/congr.py and
        left in `f.body`.  `prod=True` is the same over `prod_` (`fprodf1o`)."""
        if k == n:
            raise FSumError('the two indices must be distinct: %s, %s' % (k, n))
        ref = 'fprodf1o' if prod else 'fsumf1o'
        st, D = self._substh(B, {k: G})
        self.body = D
        self._dv(ref, {'k': k, 'n': n, 'ph': self.ante, 'A': A, 'B': B,
                       'C': C, 'D': D, 'F': F, 'G': G})
        fin = fin if fin is not None else self.cl.mem(C, 'Fin')
        b = self._bcl(self.child(k, A), B, 'CC', body, 0)
        v = self._lift(val, '( %s /\\ %s e. %s )' % (self.ante, n, C))
        S = PROD if prod else SUM
        return self._emit([st, fin, bij, v, b], ref,
                          '%s = %s' % (S(k, A, B), S(n, C, D)), name)

    def xp(self, j, A, k, B, C, z, name=None, body=None):
        """sum_ j e. A sum_ k e. B C = sum_ z e. ( A X. B ) D: two sums combined
        into one over the cartesian product.  D is C with j replaced by
        ( 1st ` z ) and k by ( 2nd ` z ), and the substitution hypothesis
        ( z = <. j , k >. -> D = C ) is written here from `op1std` / `op2ndd`.
        The substituted body is left in `f.body`."""
        if len(set([j, k, z])) != 3:
            raise FSumError('the three variables must be distinct: %s, %s, %s' % (j, k, z))
        w = self.w
        pair = '<. %s , %s >.' % (j, k)
        eq = '%s = %s' % (z, pair)
        vj = w.s([], 'vex', '%s e. _V' % j)
        vk = w.s([], 'vex', '%s e. _V' % k)
        fst, snd = '( 1st ` %s )' % z, '( 2nd ` %s )' % z
        p1 = w.s([vj, vk], 'op1std', '( %s -> %s = %s )' % (eq, fst, j))
        p2 = w.s([vj, vk], 'op2ndd', '( %s -> %s = %s )' % (eq, snd, k))
        lj = w.s([p1], 'eqcomd', '( %s -> %s = %s )' % (eq, j, fst))
        lk = w.s([p2], 'eqcomd', '( %s -> %s = %s )' % (eq, k, snd))
        gen = StepGen('x')
        cs, D = congruence(C, {j: fst, k: snd}, eq, {j: lj, k: lk}, gen)
        w.lines.extend(gen.lines)
        D = ' '.join(D.split())
        self.body = D
        if cs is None:
            st = w.s([], 'eqidd', '( %s -> %s = %s )' % (eq, D, C))
        else:
            st = w.s([cs], 'eqcomd', '( %s -> %s = %s )' % (eq, D, C))
        self._dv('fsumxp', {'j': j, 'k': k, 'z': z, 'ph': self.ante,
                            'A': A, 'B': B, 'C': C, 'D': D})
        fa = self.cl.mem(A, 'Fin'); fb = self.cl.mem(B, 'Fin')
        c = self._bcl(self.pair_child(j, A, k, B), C, 'CC', body, 0)
        return self._emit([st, fa, fb, c], 'fsumxp',
                          '%s = %s' % (SUM(j, A, SUM(k, B, C)),
                                       SUM(z, '( %s X. %s )' % (A, B), D)), name)

    def rev(self, j, M, N, K, A, k, name=None, body=None):
        """sum_ j e. ( M ... N ) A = sum_ k e. ( ( K - N ) ... ( K - M ) ) B,
        where B is A with j replaced by ( K - k )"""
        if j == k:
            raise FSumError('the two indices must be distinct: %s, %s' % (j, k))
        self._hyg(j, M, N, K); self._hyg(k, M, N, K)
        kz, mz, nz = self.cl.mem(K, 'ZZ'), self.cl.mem(M, 'ZZ'), self.cl.mem(N, 'ZZ')
        rng = '( %s ... %s )' % (M, N)
        a = self._bcl(self.child(j, rng), A, 'CC', body, 0)
        st, B = self._substh(A, {j: '( %s - %s )' % (K, k)}, prefix='r')
        self.body = B
        rng2 = '( ( %s - %s ) ... ( %s - %s ) )' % (K, N, K, M)
        return self._emit([kz, mz, nz, a, st], 'fsumrev',
                          '%s = %s' % (SUM(j, rng, A), SUM(k, rng2, B)), name)

    def prodsplit(self, k, U, A, B, C, disj, union, name=None, body=None):
        """prod_ k e. U C = ( prod_ k e. A C x. prod_ k e. B C ), from the
        steps disj: ( ante -> ( A i^i B ) = (/) ) and union: ( ante -> U = ( A u. B ) )"""
        self._hyg(k, U, A, B)
        fin = self.cl.mem(U, 'Fin')
        c = self._bcl(self.child(k, U), C, 'CC', body, 0)
        return self._emit([disj, union, fin, c], 'fprodsplit',
                          '%s = ( %s x. %s )' % (PROD(k, U, C), PROD(k, A, C), PROD(k, B, C)), name)

    def dvdsmul(self, M, N, mst, nst, gcd1, j, k, i, A, B, C, prod, name=None, body=None):
        """( sum_ j e. X A x. sum_ k e. Y B ) = sum_ i e. Z C for the divisor
        sets X, Y, Z of M, N and ( M x. N ), from `mst`/`nst` proving M, N e. NN
        and `gcd1` proving ( ante -> ( M gcd N ) = 1 ).  `C` is the summand at
        the index i; D, the summand at ( j x. k ), is generated from it by
        tools/congr.py, and `prod` proves ( ( ante /\\ ( j e. X /\\ k e. Y ) ) ->
        ( A x. B ) = D ) given the pair closure and D."""
        for v in (j, k, i):
            self._hyg(v, M, N)
        w = self.w
        X = '{ x e. NN | x || %s }' % M
        Y = '{ x e. NN | x || %s }' % N
        Z = '{ x e. NN | x || ( %s x. %s ) }' % (M, N)
        ex = w.s([], 'eqid', '%s = %s' % (X, X))
        ey = w.s([], 'eqid', '%s = %s' % (Y, Y))
        ez = w.s([], 'eqid', '%s = %s' % (Z, Z))
        ca = self._bcl(self.child(j, X), A, 'CC', body, 0)
        cb = self._bcl(self.child(k, Y), B, 'CC', body, 1)
        sub, D = self._substh(C, {i: '( %s x. %s )' % (j, k)}, prefix='d', spread=True)
        pr = (prod(self.pair_child(j, X, k, Y), D) if callable(prod)
              else self._lift(prod, self.pair_child(j, X, k, Y).ante))
        return self._emit([mst, nst, gcd1, ex, ey, ez, ca, cb, pr, sub], 'fsumdvdsmul',
                          '( %s x. %s ) = %s' % (SUM(j, X, A), SUM(k, Y, B), SUM(i, Z, C)), name)
