r"""Sortie T10: Steps23.lean (step2F, scanF and their parts) at the concrete machine.

The installation predicates of the fragments of Steps23.lean and of the callees
the earlier sorties left without one (PrimTD's ` smoothTDF ` chain, Lists'
` dropN ` , PrimList's ` coprimeToF ` , ` mulAllF ` , ` divisorsOfF ` ), in T7b's
encoding (one wff predicate per fragment, own equations, callees as predicates),
generated by a small compiler from the Lean program text (` frag ` below), the
handler ` readBraOr ` , and the frozen statements (T10-blueprint.md).
Built on tools/t9lib.py (read-only).

Steps23.lean runs on the concrete stacks ` 0 ... 7 ` ; here stack ` n ` is the
letter ` K8[n] ` (K J I I' I" I0 K0 J0), with the 28 distinctness hypotheses.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'gen'))
from t9lib import *
import t9lib as T9

S8 = lambda *ns: [K8[n] for n in ns]          # concrete stacks -> letters

# ------------------------------------------------------------ handlers and loads
RBO = 'TMrdBraOr'                              # Lean ` peekBraOr ` 's handler
NOTFL = 'if ( ( TMfl ` u ) = 1o , (/) , 1o )'
L_F0 = LSET(fl='(/)')                          # flag := false
L_T1 = LFL1                                    # flag := true
L_NOTF = LSET(fl=NOTFL)                        # flag := !flag
L_EQ = LSET(fl='if ( ( TMcmp ` u ) = 1o , 1o , (/) )')      # flag := decide ( cmp = .eq )
L_CNF = LSET(car=NOTFL, fl='(/)')              # carry := !flag , flag := false
L_TT = LSET(car='(/)', fl='1o')                # carry := false , flag := true
L_CLT = LSET(cmp='(/)')                        # cmp := .lt
L_CFL = LSET(cmp='if ( ( TMfl ` u ) = 1o , 1o , (/) )')     # cmp := if flag then .eq else .lt
P_NLT = '( u e. TMSt |-> <. 1 , if ( ( TMcmp ` u ) = (/) , (/) , 1o ) >. )'  # bit ( decide ( cmp =/= lt ) )
BIT0_, BIT1_ = '<. 1 , (/) >.', '<. 1 , 1o >.'


def RBO_EVAL(v, o):
    """the value of ` readBraOr v o ` : ` flag := v.flag || decide ( o = some bra ) ` """
    return MK(*([FLD(f, v) for f in ORDER[:6]] +
                ['if ( ( ( TMfl ` %s ) = 1o \\/ %s = ( inl ` 2 ) ) , 1o , (/) )' % (v, o)]))


DF_RBO = '%s = ( v e. TMSt , o e. %s |-> %s )' % (RBO, OPT, RBO_EVAL('v', 'o'))


# ------------------------------------------------------------ the fragment compiler
# nodes: ('call', fname, ks) | ('push', k, sym) | ('pushf', k, fn) | ('peek', k, h) | ('pop', k, h)
#        | ('load', f) | ('skip',) | ('seq', a, b, ...) | ('ite', c, F, G) | ('loop', c, B)
def call(f, ks): return ('call', f, list(ks))
def seq(*xs): return ('seq',) + tuple(xs)
def ite(c, a, b): return ('ite', c, a, b)
def loop(c, b): return ('loop', c, b)
def push(k, z): return ('push', k, z)
def load(f): return ('load', f)
SKIP = ('skip',)
def peekbra(k): return ('peek', k, 'TMrdBra')
def peekbraor(k): return ('peek', k, RBO)
def poptop(k): return ('pop', k, PID)


def pushnum(k, c):
    """Lean ` pushNum k c = pushTerm k ( encodeNatΓ' c ) ` : comma, then the bits from the last one"""
    bits = []
    n = c
    while n > 0:
        bits.append(n % 2); n //= 2
    return seq(*([push(k, '4')] + [push(k, BIT1_ if b else BIT0_) for b in reversed(bits)])) if bits else push(k, '4')


def forentries(x, body):
    """Lean ` forEntries x body = peekBra x ; loop ( !flag ) ( body ; peekBra x ) ` """
    return seq(peekbra(x), loop(CNFL, seq(body, peekbra(x))))


class _C:
    """two passes: names in program order (own labels Z1 Z2 ..., callee entries Y1 Y2 ...), then the
    equations with their continuations"""
    def __init__(self):
        self.labels, self.eqs, self.children, self.n, self.m = [], [], [], 0, 0
        self.ent = {}
        self.cslot = {}

    def name(self, t):
        """phase 1: the entry name of every node, in program order"""
        op = t[0]
        if op == 'seq':
            for x in t[1:]:
                self.name(x)
            self.ent[id(t)] = self.ent[id(t[1])]
            return
        if op == 'call':
            self.m += 1
            en = 'Y%d' % self.m
            self.ent[id(t)] = en
            self.cslot[id(t)] = len(self.children)
            self.children.append(None)
            return
        self.n += 1
        L = 'Z%d' % self.n
        self.ent[id(t)] = L
        self.labels.append(L)
        if op == 'ite':
            self.name(t[2]); self.name(t[3])
        elif op == 'loop':
            self.name(t[2])

    def go(self, t, k):
        """phase 2: compile t with continuation label k; return the entry name"""
        op = t[0]
        if op == 'seq':
            e = k
            for x in reversed(t[1:]):
                e = self.go(x, e)
            return e
        if op == 'call':
            en = self.ent[id(t)]
            self.children[self.cslot[id(t)]] = (t[1], t[2], en, k)
            return en
        L = self.ent[id(t)]
        if op == 'push':
            st = PUSH(t[1], CONST(t[2]), GT(k))
        elif op == 'pushf':
            st = PUSH(t[1], t[2], GT(k))
        elif op == 'peek':
            st = PEEK(t[1], t[2], GT(k))
        elif op == 'pop':
            st = POP(t[1], t[2], GT(k))
        elif op == 'load':
            st = LOAD(t[1], GT(k))
        elif op == 'skip':
            st = LOAD(LID, GT(k))
        elif op == 'ite':
            a = self.go(t[2], k)
            b = self.go(t[3], k)
            st = BRANCH(t[1], GT(a), GT(b))
        elif op == 'loop':
            b = self.go(t[2], L)
            st = BRANCH(t[1], GT(b), GT(k))
        else:
            raise ValueError(op)
        self.eqs.append((L, MEQ(L, st)))
        return L


def frag(name, const, ks, prog, lean):
    """register the installation predicate of the fragment ` prog ` (a node tree over the letters ks)"""
    c = _C()
    c.name(prog)
    entry = c.go(prog, 'E')
    labels = list(c.labels)
    start = None
    if entry in labels:
        labels.remove(entry)
        labels = [entry] + labels
    else:
        start = entry
    byl = dict(c.eqs)
    progt = grp([byl[l] for l in labels]) if labels else None
    labt = grp([LAB(l) for l in labels] + [LAB('E')]) if labels else None
    f = comp(name, const, ks, labels, 'E', progt, labt, lean, c.children)
    if start is not None:
        f.start = start
    return f


# The fragments.  Every predicate of this sortie is at the stacks of its one call in the final
# program (the numerals 0 ... 7 of Steps23.lean), so it takes no stack argument: ` TMIxxx T M P E `
# (mmj2 derives 2 ^ k notation rules for a syntax axiom with k class arguments; 33 predicates with
# 10-12 arguments exhaust its parser, blueprint D2).
N = lambda *ns: [str(n) for n in ns]
N8 = N(0, 1, 2, 3, 4, 5, 6, 7)

# ------------------------------------------------------------ PrimTD at smoothTDF 0 6 4 7 1 2 3
# divOutF xd xr xf s t u = 4 6 7 1 2 3 ; smoothGoF xd xr xf xF s t u = 4 6 7 0 1 2 3
frag('dot', 'TMIdot', [],
     seq(call('dup', N(6, 1, 2)), call('dup', N(4, 2, 1)), call('dmcc', N(1, 2, 3, 4, 7, 6)),
         call('iz', N(1, 2)), call('drop', N(1)),
         ite('TMfl', seq(call('iz', N(7, 1)), load(L_NOTF)), SKIP)),
     "` divOutTest xd xr xf s t u = dup xr s t ; dup xd t s ; divmodC s t u xd xf xr ; isZero s t ; dropNum s ; "
     "ite flag ( isZero xf s ; load' ( flag := !flag ) ) skip ` at ` xd xr xf s t u = 4 6 7 1 2 3 `")
frag('dob', 'TMIdob', [],
     seq(call('drop', N(6)), call('me', N(3, 6, 1)), call('prd', N(7, 1)), call('dot', [])),
     "` divOutBody xd xr xf s t u = dropNum xr ; moveEntry u xr s ; predNum xf s ; divOutTest xd xr xf s t u ` "
     "at ` 4 6 7 1 2 3 `")
frag('dof', 'TMIdof', [],
     seq(call('dot', []), loop('TMfl', call('dob', [])), call('drop', N(3))),
     "` divOutF xd xr xf s t u = divOutTest xd xr xf s t u ; loop flag ( divOutBody xd xr xf s t u ) ; dropNum u ` "
     "at ` 4 6 7 1 2 3 `")
frag('sgb', 'TMIsgb', [],
     seq(call('dup', N(6, 7, 1)), call('dof', []), call('drop', N(7)), call('inc', N(4, 1)),
         call('prd', N(0, 1)), call('iz', N(0, 1))),
     "` smoothGoBody xd xr xf xF s t u = dup xr xf s ; divOutF xd xr xf s t u ; dropNum xf ; incr xd s ; "
     "predNum xF s ; isZero xF s ` at ` xd xr xf xF s t u = 4 6 7 0 1 2 3 `")
frag('sgf', 'TMIsgf', [],
     seq(call('iz', N(0, 1)), loop(CNFL, call('sgb', []))),
     "` smoothGoF xd xr xf xF s t u = isZero xF s ; loop ( !flag ) ( smoothGoBody xd xr xf xF s t u ) ` "
     "at ` 4 6 7 0 1 2 3 `")
frag('std', 'TMIstd', [],
     seq(call('dup', N(0, 1, 2)), call('prd', N(1, 2)), call('me', N(1, 0, 2)), pushnum('4', 2),
         call('sgf', []), call('drop', N(0)), call('drop', N(4)), pushnum('1', 1),
         call('cmp', N(6, 1)), load(L_EQ)),
     "` smoothTDF xy xr xd xf s t u = dup xy s t ; predNum s t ; moveEntry s xy t ; pushNum xd 2 ; "
     "smoothGoF xd xr xf xy s t u ; dropNum xy ; dropNum xd ; pushNum s 1 ; cmpFrag xr s ; "
     "load' ( flag := decide ( cmp = .eq ) ) ` at ` xy xr xd xf s t u = 0 6 4 7 1 2 3 `")

# ------------------------------------------------------------ Lists: dropN 4 5 6 (x c s)
frag('dnb', 'TMIdnb', [],
     seq(call('drop', N(4)), call('prd', N(5, 6)), call('iz', N(5, 6)), peekbraor('4')),
     "` dropNBody x c s = dropNum x ; predNum c s ; isZero c s ; peekBraOr x ` at ` x c s = 4 5 6 `")
frag('dn', 'TMIdn', [],
     seq(call('iz', N(5, 6)), peekbraor('4'), loop(CNFL, call('dnb', [])), call('drop', N(5))),
     "` dropN x c s = isZero c s ; peekBraOr x ; loop ( !flag ) ( dropNBody x c s ) ; dropNum c ` at ` 4 5 6 `")

# ------------------------------------------------------------ PrimList: coprimeToF 4 2 3 5 6 7 (x y z s t u)
frag('cpb', 'TMIcpb', [],
     seq(call('dup', N(4, 6, 5)), call('dup', N(2, 7, 5)), call('modc', N(7, 6, 4, 2, 3, 5)), call('iz', N(7, 5)),
         load(L_CFL), call('drop', N(7)), call('me', N(4, 3, 5)), peekbraor('4')),
     "` cpBody x y z s t u = dup x t s ; dup y u s ; modC u t x y z s ; isZero u s ; "
     "load' ( cmp := if flag then .eq else .lt ) ; dropNum u ; moveEntry x z s ; peekBraOr x ` "
     "at ` x y z s t u = 4 2 3 5 6 7 `")
frag('cpt', 'TMIcpt', [],
     seq(push('3', '2'), load(L_CLT), peekbra('4'), loop(CNFL, call('cpb', [])), push('6', '4'), ('pushf', '6', P_NLT),
         forentries('3', call('me', N(3, 4, 5))), poptop('3'), call('iz', N(6, 5)), call('drop', N(6))),
     "` coprimeToF x y z s t u = pushSym z bra ; load' ( cmp := .lt ) ; peekBra x ; loop ( !flag ) ( cpBody x y z s t u ) ; "
     "pushSym t comma ; pushBit t ( decide ( cmp =/= .lt ) ) ; moveEntries z x s ; isZero t s ; dropNum t ` , "
     "` moveEntries src dst s = forEntries src ( moveEntry src dst s ) ; popTop src ` (inline), at ` 4 2 3 5 6 7 `")
# divisorsOfF 5 3 7 6 0 1 (x z a c s t); mulAllF c z x s t = 6 3 5 0 1 (x y r s t)
frag('mab', 'TMImab', [],
     seq(call('dup', N(3, 1, 0)), call('mulc', N(6, 1, 5, 0, 3))),
     "` mulAllBody x y r s t = dup y t s ; mulC x t r s y ` at ` x y r s t = 6 3 5 0 1 `")
frag('maf', 'TMImaf', [],
     seq(push('5', '2'), forentries('6', call('mab', [])), poptop('6'), call('lrev', N(5, 6, 0))),
     "` mulAllF x y r s t = pushSym r bra ; forEntries x ( mulAllBody x y r s t ) ; popTop x ; revList r x s ` "
     "at ` 6 3 5 0 1 `")
frag('dvb', 'TMIdvb', [],
     seq(call('lcpy', N(7, 6, 0, 1)), call('maf', []), call('lapp', N(6, 7, 0, 1)), call('drop', N(3))),
     "` divBody x z a c s t = copyList a c s t ; mulAllF c z x s t ; appendList c a t s ; dropNum z ` "
     "at ` x z a c s t = 5 3 7 6 0 1 ` ( ` TMIlapp ` takes ` appendList x y z s ` as ` x y s z ` )")
frag('dvs', 'TMIdvs', [],
     seq(call('lrev', N(5, 3, 0)), push('7', '2'), pushnum('7', 1), forentries('3', call('dvb', [])), poptop('3'),
         call('lrev', N(7, 5, 0))),
     "` divisorsOfF x z a c s t = revList x z s ; pushSym a bra ; pushNum a 1 ; forEntries z ( divBody x z a c s t ) ; "
     "popTop z ; revList a x s ` at ` 5 3 7 6 0 1 `")

# ------------------------------------------------------------ Steps23: step 2
frag('kp', 'TMIkp', [],
     seq(call('dup', N(1, 6, 7)), call('dup', N(2, 7, 6)), call('cmp', N(6, 7)),
         ite(CLT, seq(call('ipt', N(2, 4, 6, 7, 3, 1)),
                      ite('TMfl', seq(call('dup', N(2, 6, 7)), call('prd', N(6, 7)), call('std', [])), SKIP)),
             load(L_F0))),
     "` keepF = dup 1 6 7 ; dup 2 7 6 ; cmpFrag 6 7 ; ite ( cmp = lt ) ( isPrimeTDF 2 4 6 7 3 1 ; "
     "ite flag ( dup 2 6 7 ; predNum 6 7 ; smoothTDF 0 6 4 7 1 2 3 ) skip ) ( load' ( flag := false ) ) `")
frag('rts', 'TMIrts', [], seq(call('kp', []), ite('TMfl', call('dup', N(2, 5, 6)), SKIP)),
     "` resTestF = keepF ; ite flag ( dup 2 5 6 ) skip `")
frag('rgb', 'TMIrgb', [], seq(call('rts', []), call('inc', N(2, 6)), call('prd', N(3, 6)), call('iz', N(3, 6))),
     "` resGoBody = resTestF ; incr 2 6 ; predNum 3 6 ; isZero 3 6 `")
frag('rgf', 'TMIrgf', [], seq(call('iz', N(3, 6)), loop(CNFL, call('rgb', [])), call('lrev', N(5, 4, 6))),
     "` resGoF = isZero 3 6 ; loop ( !flag ) resGoBody ; revList 5 4 6 `")
frag('rsv', 'TMIrsv', [],
     seq(call('prd', N(3, 6)), pushnum('2', 2), push('5', '2'), call('rgf', []), call('drop', N(2)), call('drop', N(3))),
     "` reservoirF = predNum 3 6 ; pushNum 2 2 ; pushSym 5 bra ; resGoF ; dropNum 2 ; dropNum 3 `")
frag('scx', 'TMIscx', [], seq(call('sub', N(5, 6, 7)), call('can', N(5, 7))),
     "` subCx x y z = sub x y z x ; canonNum x z ` at ` x y z = 5 6 7 `")
frag('p5', 'TMIp5', [],
     seq(call('dup', N(3, 5, 6)), call('dup', N(3, 6, 5)), call('mulc', N(5, 6, 7, 2, 4)), call('dup', N(3, 5, 6)),
         call('mulc', N(7, 5, 6, 2, 4)), call('dup', N(3, 5, 7)), call('mulc', N(6, 5, 7, 2, 4)), call('dup', N(3, 5, 6)),
         call('mulc', N(7, 5, 6, 2, 4))),
     "` pow5F = dup 3 5 6 ; dup 3 6 5 ; mulC 5 6 7 2 4 ; dup 3 5 6 ; mulC 7 5 6 2 4 ; dup 3 5 7 ; mulC 6 5 7 2 4 ; "
     "dup 3 5 6 ; mulC 7 5 6 2 4 `")
frag('s2p', 'TMIs2p', [],
     seq(call('dup', N(0, 3, 5)), call('me', N(0, 1, 5)), call('me', N(0, 1, 5)), call('rsv', []), call('drop', N(1)),
         call('drop', N(0)), call('llen', N(4, 2, 5, 6)), call('dup', N(2, 5, 6)), call('dup', N(0, 6, 5)), call('cmp', N(5, 6))),
     "` step2Pre = dup 0 3 5 ; moveEntry 0 1 5 ; moveEntry 0 1 5 ; reservoirF ; dropNum 1 ; dropNum 0 ; "
     "listLen 4 2 5 6 ; dup 2 5 6 ; dup 0 6 5 ; cmpFrag 5 6 `")
frag('s2s', 'TMIs2s', [],
     seq(call('dup', N(2, 5, 6)), call('dup', N(0, 6, 5)), call('scx', []), call('dn', []),
         call('drop', N(2)), call('prl', N(4, 3, 5, 6, 7)), call('p5', []), call('drop', N(0)), call('me', N(1, 5, 7)),
         call('dup', N(6, 1, 7)), call('me', N(5, 1, 7)), call('me', N(6, 0, 5)), pushnum('2', 1), load(L_T1)),
     "` step2Succ = dup 2 5 6 ; dup 0 6 5 ; subCx 5 6 7 ; dropN 4 5 6 ; dropNum 2 ; prodLF 4 3 5 6 7 ; pow5F ; "
     "dropNum 0 ; moveEntry 1 5 7 ; dup 6 1 7 ; moveEntry 5 1 7 ; moveEntry 6 0 5 ; pushNum 2 1 ; "
     "load' ( flag := true ) `")
frag('s2f', 'TMIs2f', [], seq(call('s2p', []), ite(CLT, load(L_F0), call('s2s', []))),
     "` step2F = step2Pre ; ite ( cmp = lt ) ( load' ( flag := false ) ) step2Succ `")

# ------------------------------------------------------------ Steps23: step 3
frag('ppr', 'TMIppr', [],
     seq(call('dup', N(2, 4, 6)), call('mulc', N(5, 4, 7, 6, 3)), call('inc', N(7, 4)), call('dup', N(7, 4, 6)),
         call('dup', N(0, 6, 4)), call('cmp', N(4, 6))),
     "` poolPre = dup 2 4 6 ; mulC 5 4 7 6 3 ; incr 7 4 ; dup 7 4 6 ; dup 0 6 4 ; cmpFrag 4 6 `")
frag('pcz', 'TMIpcz', [], seq(call('dup', N(1, 4, 6)), call('dup', N(7, 6, 4)), call('cmp', N(4, 6))),
     "` poolCmpZ = dup 1 4 6 ; dup 7 6 4 ; cmpFrag 4 6 `")
frag('plb', 'TMIplb', [],
     seq(call('ppr', []),
         ite(CNGT,
             seq(call('pcz', []),
                 ite(CLT, seq(call('ipt', N(7, 4, 6, 0, 1, 2)), ite('TMfl', call('me', N(7, 3, 4)), call('drop', N(7)))),
                     call('drop', N(7)))),
             call('drop', N(7)))),
     "` poolGoBody = poolPre ; ite ( !decide ( cmp = gt ) ) ( poolCmpZ ; ite ( cmp = lt ) ( isPrimeTDF 7 4 6 0 1 2 ; "
     "ite flag ( moveEntry 7 3 4 ) ( dropNum 7 ) ) ( dropNum 7 ) ) ( dropNum 7 ) `")
frag('plf', 'TMIplf', [], seq(push('3', '2'), forentries('5', call('plb', [])), poptop('5'), call('lrev', N(3, 6, 4))),
     "` poolGoF = pushSym 3 bra ; forEntries 5 poolGoBody ; popTop 5 ; revList 3 6 4 `")
frag('pla', 'TMIpla', [], seq(call('lcpy', N(4, 5, 7, 3)), call('dvs', []), call('plf', [])),
     "` poolAlgF = copyList 4 5 7 3 ; divisorsOfF 5 3 7 6 0 1 ; poolGoF `")
frag('scn', 'TMIscn', [],
     seq(call('inc', N(2, 5)), call('me', N(1, 7, 5)), call('prd', N(1, 5)), call('iz', N(1, 5)), call('me', N(7, 1, 5)),
         load(L_CNF)),
     "` scanNext = incr 2 5 ; moveEntry 1 7 5 ; predNum 1 5 ; isZero 1 5 ; moveEntry 7 1 5 ; "
     "load' ( carry := !flag , flag := false ) `")
frag('sct', 'TMIsct', [],
     seq(call('pla', []), call('llen', N(6, 3, 7, 5)), call('me', N(0, 7, 5)), call('dup', N(0, 5, 4)), call('me', N(7, 0, 5)),
         call('cmp', N(5, 3))),
     "` scanTest = poolAlgF ; listLen 6 3 7 5 ; moveEntry 0 7 5 ; dup 0 5 4 ; moveEntry 7 0 5 ; cmpFrag 5 3 `")
frag('scb', 'TMIscb', [],
     seq(call('cpt', []),
         ite('TMfl', seq(call('sct', []), ite(CNGT, load(L_TT), seq(call('dpl', N(6)), call('scn', [])))),
             call('scn', []))),
     "` scanBody = coprimeToF 4 2 3 5 6 7 ; ite flag ( scanTest ; ite ( !decide ( cmp = gt ) ) "
     "( load' ( carry := false , flag := true ) ) ( dropListQ 6 ; scanNext ) ) scanNext ` "
     "( ` dropListQ ` is T8a's ` dropList ` , ` TMIdpl ` )")
frag('scf', 'TMIscf', [],
     seq(call('me', N(1, 7, 5)), call('iz', N(1, 5)), call('me', N(7, 1, 5)), load(L_CNF), loop('TMcar', call('scb', [])),
         call('me', N(1, 7, 5)), call('drop', N(1)), call('me', N(7, 1, 5))),
     "` scanF = moveEntry 1 7 5 ; isZero 1 5 ; moveEntry 7 1 5 ; load' ( carry := !flag , flag := false ) ; "
     "loop carry scanBody ; moveEntry 1 7 5 ; dropNum 1 ; moveEntry 7 1 5 `")

PREDS10 = ['dot', 'dob', 'dof', 'sgb', 'sgf', 'std', 'dnb', 'dn', 'cpb', 'cpt', 'mab', 'maf', 'dvb', 'dvs',
           'kp', 'rts', 'rgb', 'rgf', 'rsv', 'scx', 'p5', 's2p', 's2s', 's2f',
           'ppr', 'pcz', 'plb', 'plf', 'pla', 'scn', 'sct', 'scb', 'scf']


# ============================================================ statements (T10-blueprint.md section 2)
IFV = lambda c, a, b: 'if ( %s , %s , %s )' % (c, a, b)
DK = lambda k: '( D ` %s )' % k
LT2 = lambda a, b='B': '%s < ( 2 ^ %s )' % (a, b)
CS = lambda fname: CEN9(fname, 'D')                 # the entry class C( entry , S , D )
TMBx = lambda x: '( TMB ` %s )' % x
DEQ = lambda k, v: '( D ` %s ) = %s' % (k, v)
# the stack facts at the numerals: every index in ( 0 ..^ 8 ) , every pair distinct (proved once, t10stk)
NUMS = (idx_tree(N8), dist_tree(N8))
ST_NUMS = cj(NUMS)


def TREE0(fname, data):
    """the antecedent: the machine, the predicate, the data (no stack index: the stacks are numerals)"""
    return ((T_PHM7, FRAGS[fname].pred()), data)


# ------------------------------------------------------------ smoothTDF_le_B at xy xr xd xf s t u = 0 6 4 7 1 2 3
STD_ = '( Y SmoothTD F )'
DATA_STD = ((STKD('D'), ('Y e. NN', 'F e. NN0', 'B e. NN0'), ('2 <_ B', LT2('Y'), LT2('F'))),
            (WG('X'), WG("X'")), (DEQ(0, EWg('Y', 'X')), DEQ(6, EWg('F', "X'"))))
TREE_STD = TREE0('std', DATA_STD)
CONCL_STD = TRI(CS('std'), CLN('E', NFL('( 1st ` %s )' % STD_), UP('D', '6', "X'")),
                '( ( ( 2nd ` %s ) + 1 ) x. %s )' % (STD_, TMBx('( ( 4 x. B ) + ; 1 0 )')))

# ------------------------------------------------------------ divOutF_le_B at xd xr xf s t u = 4 6 7 1 2 3
DO_ = '( ( G DivOut F ) ` H )'
DATA_DOF = ((STKD('D'), ('G e. NN', 'F e. NN0', 'H e. NN0'), ('B e. NN0', LT2('G'), LT2('F'))),
            ((LT2('H'), WG('X')), (WG("X'"), WG('Y'))),
            (DEQ(4, EWg('G', 'X')), DEQ(6, EWg('F', "X'")), DEQ(7, EWg('H', 'Y'))))
TREE_DOF = TREE0('dof', DATA_DOF)
CONCL_DOF = TRI(CS('dof'), CLN('E', S, UPS('D', ('6', EWg('( 1st ` %s )' % DO_, "X'")),
                                          ('7', EWg('( H - ( 2nd ` %s ) )' % DO_, 'Y')))),
                '( ( ( 2nd ` %s ) + 1 ) x. %s )' % (DO_, TMBx('( ( 3 x. B ) + 4 )')))

# ------------------------------------------------------------ smoothGoF_le_B at xd xr xf xF s t u = 4 6 7 0 1 2 3
SG_ = '( ( G SmoothGo F ) ` H )'
DATA_SGF = ((STKD('D'), ('G e. NN', 'F e. NN0', 'H e. NN0'), ('B e. NN0', LT2('G'), LT2('F'))),
            ((LT2('H'), WG('X')), (WG("X'"), WG('Y'))),
            (DEQ(4, EWg('G', 'X')), DEQ(6, EWg('F', "X'")), DEQ(0, EWg('H', 'Y'))))
TREE_SGF = TREE0('sgf', DATA_SGF)
CONCL_SGF = TRI(CS('sgf'), CLN('E', S, UPS('D', ('0', EWg('0', 'Y')), ('4', EWg('( G + H )', 'X')),
                                          ('6', EWg('( 1st ` %s )' % SG_, "X'")))),
                '( ( ( 2nd ` %s ) + 1 ) x. %s )' % (SG_, TMBx('( ( 4 x. B ) + ; 1 0 )')))

# ------------------------------------------------------------ dropN_le_B at x c s = 4 5 6
DATA_DN = ((STKD('D'), ('W e. Word NN0', 'N e. NN0', 'B e. NN0'), (RALB('W'), LT2('N'), 'N <_ ( # ` W )')),
           (WG('X'), WG('Y')), (DEQ(4, ENCL('W', 'X')), DEQ(5, EWg('N', 'Y'))))
TREE_DN = TREE0('dn', DATA_DN)
CONCL_DN = TRI(CS('dn'), CLN('E', S, UPS('D', ('4', ENCL('( W substr <. N , ( # ` W ) >. )', 'X')), ('5', 'Y'))),
               '( ( ( # ` W ) + 1 ) x. ( 4 x. ( TMB ` B ) ) )')

# ------------------------------------------------------------ subCx_le_B at x y z = 5 6 7
DATA_SCX = ((STKD('D'), ('F e. NN0', 'G e. NN0', 'N e. NN0'), (LT2('F', 'N'), LT2('G', 'N'), 'G <_ F')),
            (WG('X'), WG('Y')), (DEQ(5, EWg('F', 'X')), DEQ(6, EWg('G', 'Y'))))
TREE_SCX = TREE0('scx', DATA_SCX)
CONCL_SCX = TRI(CS('scx'), CLN('E', S, UPS('D', ('5', EWg('( F - G )', 'X')), ('6', 'Y'))), '( TMB ` N )')

# ------------------------------------------------------------ pow5F_le_B
DATA_P5 = ((STKD('D'), ('L e. NN0', 'N e. NN0', LT2('L', 'N'))), (WG('X'), DEQ(3, EWg('L', 'X'))))
TREE_P5 = TREE0('p5', DATA_P5)
CONCL_P5 = TRI(CS('p5'), CLN('E', S, UP('D', '6', EWg('( L ^ 5 )', DK(6)))), '( 9 x. ( TMB ` ( 4 x. N ) ) )')

# ------------------------------------------------------------ keepF_runs: z99 = G , y = Y , q' = Q
RK_ = IFV('G < Q', IFV('( 1st ` ( IsPrimeTD ` Q ) ) = 1o', '( 1st ` ( Y SmoothTD ( Q - 1 ) ) )', '(/)'), '(/)')
DATA_KP = ((STKD('D'), ('G e. NN0', 'Y e. NN', 'Q e. NN'), ('B e. NN0', '2 <_ B')),
           ((LT2('G'), LT2('Y'), LT2('Q')), (WG('X'), WG("X'"), WG('Z'))),
           (DEQ(0, EWg('Y', 'X')), DEQ(1, EWg('G', "X'")), DEQ(2, EWg('Q', 'Z'))))
TREE_KP = TREE0('kp', DATA_KP)
KPB = ('( ( ( ( ( ( 2nd ` ( IsPrimeTD ` Q ) ) + 1 ) x. %s ) + ( ( ( 2nd ` ( Y SmoothTD ( Q - 1 ) ) ) + 1 ) x. %s ) ) '
       '+ ( 5 x. ( TMB ` B ) ) ) + 2 )' % (TMBx('( ( 3 x. B ) + 7 )'), TMBx('( ( 4 x. B ) + ; 1 0 )')))
CONCL_KP = TRI(CS('kp'), CLN('E', NFL(RK_), 'D'), KPB)

# ------------------------------------------------------------ resTestF_runs
TREE_RTS = TREE0('rts', DATA_KP)
RTSB = ('( ( ( ( ( ( 2nd ` ( IsPrimeTD ` Q ) ) + 1 ) x. %s ) + ( ( ( 2nd ` ( Y SmoothTD ( Q - 1 ) ) ) + 1 ) x. %s ) ) '
        '+ ( 6 x. ( TMB ` B ) ) ) + 3 )' % (TMBx('( ( 3 x. B ) + 7 )'), TMBx('( ( 4 x. B ) + ; 1 0 )')))
CONCL_RTS = TRI(CS('rts'), CLN('E', S, UP('D', '5', IFV('%s = 1o' % RK_, EWg('Q', DK(5)), DK(5)))), RTSB)

# ------------------------------------------------------------ resGoF_runs: z99 = G , y = Y , q = Q , fuel = H
RG_ = '( ( ( G ResGo Y ) ` Q ) ` H )'
DATA_RGF = ((STKD('D'), ('G e. NN0', 'Y e. NN', 'Q e. NN'), ('H e. NN0', 'B e. NN0', '2 <_ B')),
            ((LT2('G'), LT2('Y'), LT2('( Q + H )')), ((WG('X'), WG("X'")), (WG('Z'), WG("Z'"), WG('R')))),
            ((DEQ(0, EWg('Y', 'X')), DEQ(1, EWg('G', "X'"))),
             (DEQ(2, EWg('Q', 'Z')), DEQ(3, EWg('H', "Z'")), DEQ(5, '( <" 2 "> ++ R )'))))
TREE_RGF = TREE0('rgf', DATA_RGF)
CONCL_RGF = TRI(CS('rgf'), CLN('E', S, UPS('D', ('2', EWg('( Q + H )', 'Z')), ('3', EWg('0', "Z'")),
                                          ('4', ENCL('( 1st ` %s )' % RG_, DK(4))), ('5', 'R'))),
                '( ( ( 2nd ` %s ) + 1 ) x. ( ; 1 1 x. %s ) )' % (RG_, TMBx('( ( 4 x. B ) + ; 1 0 )')))

# ------------------------------------------------------------ reservoirF_runs: z = Z , z99 = G , y = Y
RSV_ = '( ( Z Reservoir G ) ` Y )'
DATA_RSV = ((STKD('D'), ('Z e. NN', 'G e. NN0', 'Y e. NN'), ('B e. NN0', '2 <_ B')),
            ((LT2('Z'), LT2('G'), LT2('Y')), (WG('X'), WG("X'"), WG('Z"'))),
            (DEQ(0, EWg('Y', 'X')), DEQ(1, EWg('G', "X'")), DEQ(3, EWg('Z', 'Z"'))))
TREE_RSV = TREE0('rsv', DATA_RSV)
RSVX = TMBx('( ( 4 x. B ) + ; 1 4 )')
CONCL_RSV = TRI(CS('rsv'), CLN('E', S, UPS('D', ('3', 'Z"'), ('4', ENCL('( 1st ` %s )' % RSV_, DK(4))))),
                '( ( ( ( 2nd ` %s ) + 1 ) x. ( ; 1 1 x. %s ) ) + ( ( 3 x. %s ) + 7 ) )' % (RSV_, RSVX, RSVX))

# ------------------------------------------------------------ step 2: z = Z , z99 = G , y = Y , T = U , theta = O
RL_ = '( 1st ` %s )' % RSV_
LEN_ = '( # ` %s )' % RL_
RC_ = '( 2nd ` %s )' % RSV_
QQ_ = '( %s substr <. ( %s - U ) , %s >. )' % (RL_, LEN_, LEN_)
LL_ = '( 1st ` ( ProdL ` %s ) )' % QQ_
X5_ = '( %s ^ 5 )' % LL_
FAIL_ = '%s < U' % LEN_
EWUO = EWg('U', EWg('O', 'R'))
DATA_S2 = ((STKD('D'), ('Z e. NN', 'G e. NN0', 'Y e. NN'), ('U e. NN0', 'O e. NN0', 'B e. NN0')),
           (('2 <_ B', WG('R')), (LT2('Z'), LT2('G')), (LT2('Y'), LT2('U'))),
           DEQ(0, EWg('Z', EWg('G', EWg('Y', EWUO)))))
TREE_S2P = TREE0('s2p', DATA_S2)
CONCL_S2P = TRI(CS('s2p'), CLN('E', '{ h e. TMSt | ( TMcmp ` h ) = ( %s Ncmp U ) }' % LEN_,
                              UPS('D', ('0', EWUO), ('1', EWg('Z', DK(1))), ('2', EWg(LEN_, DK(2))),
                                  ('4', ENCL(RL_, DK(4))))),
                '( ( %s + 2 ) x. ( ; 1 2 x. %s ) )' % (RC_, TMBx('( ( 4 x. B ) + ; 1 4 )')))
TREE_S2F = TREE0('s2f', DATA_S2)
S2COST = IFV(FAIL_, '( %s + 1 )' % RC_, '( ( %s + ( 2 x. U ) ) + 2 )' % RC_)
DFIN_S2F = UPS('D', ('0', IFV(FAIL_, EWUO, EWg(X5_, EWg('O', 'R')))),
               ('1', IFV(FAIL_, EWg('Z', DK(1)), EWg('Z', EWg(X5_, DK(1))))),
               ('2', IFV(FAIL_, EWg(LEN_, DK(2)), EWg('1', DK(2)))),
               ('3', IFV(FAIL_, DK(3), EWg(LL_, DK(3)))),
               ('4', IFV(FAIL_, ENCL(RL_, DK(4)), ENCL(QQ_, DK(4)))))
CONCL_S2F = TRI(CS('s2f'), CLN('E', NFL(IFV(FAIL_, '(/)', '1o')), DFIN_S2F),
                '( ( %s + 1 ) x. %s )' % (S2COST, TMBx('( ( ( ; 1 5 x. ( U + 1 ) ) x. B ) + ; 4 6 )')))

# step2Succ_runs: res = W , z = Z , T = U , theta = O
QS_ = '( W substr <. ( ( # ` W ) - U ) , ( # ` W ) >. )'
LS_ = '( 1st ` ( ProdL ` %s ) )' % QS_
X5S_ = '( %s ^ 5 )' % LS_
DATA_S2S = ((STKD('D'), ('W e. Word NN0', 'Z e. NN0', 'U e. NN0'), ('O e. NN0', 'B e. NN0', '2 <_ B')),
            ((RALB('W'), LT2('( # ` W )'), LT2('U')), ('U <_ ( # ` W )', LT2('Z')),
             ((WG('R'), WG("R'")), (WG('R"'), WG('Y')))),
            ((DEQ(0, EWUO), DEQ(1, EWg('Z', "R'"))), (DEQ(2, EWg('( # ` W )', 'R"')), DEQ(4, ENCL('W', 'Y')))))
TREE_S2S = TREE0('s2s', DATA_S2S)
CONCL_S2S = TRI(CS('s2s'), CLN('E', NFL('1o'),
                              UPS('D', ('0', EWg(X5S_, EWg('O', 'R'))), ('1', EWg('Z', EWg(X5S_, "R'"))),
                                  ('2', EWg('1', 'R"')), ('3', EWg(LS_, DK(3))), ('4', ENCL(QS_, 'Y')))),
                '( ( ( ( # ` W ) + U ) + ; 2 1 ) x. %s )' % TMBx('( ( ( 5 x. ( U + 1 ) ) x. B ) + ; 1 4 )'))

# ------------------------------------------------------------ scanF_le_B: Q = W , x = F , z = Z , theta = O ,
# k = G , fuel = H , bq = C , b = B
SC_ = '( ( ( ( ( W Scan F ) ` Z ) ` O ) ` G ) ` H )'
SCO_ = '( 1st ` %s )' % SC_
NONE_ = '%s = ( inr ` (/) )' % SCO_
DATA_SCF = (((STKD('D'), 'W e. Word NN0', ('F e. NN0', 'Z e. NN0', 'O e. NN0')),
             (('G e. NN0', 'H e. NN0'), ('C e. NN0', 'B e. NN0')),
             ((RALB('W', 'C'), 'A. a e. ran W 1 <_ a'), (LT2('F'), LT2('Z')), (LT2('O'), LT2('( G + H )')))),
            ((WG('X'), WG("X'")), (WG('Y'), WG("Y'"))),
            ((DEQ(0, EWg('F', EWg('O', 'X'))), DEQ(1, EWg('Z', EWg('H', "X'")))),
             (DEQ(2, EWg('G', 'Y')), DEQ(4, ENCL('W', "Y'")))))
TREE_SCF = TREE0('scf', DATA_SCF)
DFIN_SCF = UPS('D', ('1', EWg('Z', "X'")),
               ('2', IFV(NONE_, EWg('( G + H )', 'Y'), EWg('( 1st ` ( 2nd ` %s ) )' % SCO_, 'Y'))),
               ('6', IFV(NONE_, DK(6), ENCL('( 2nd ` ( 2nd ` %s ) )' % SCO_, DK(6)))))
CONCL_SCF = TRI(CS('scf'), CLN('E', NFL(IFV(NONE_, '(/)', '1o')), DFIN_SCF),
                '( ( ( 2nd ` %s ) + 1 ) x. %s )'
                % (SC_, TMBx('( ( ( ( ; 4 8 x. ( ( # ` W ) + 1 ) ) x. ( C + B ) ) + ( 4 x. ( # ` W ) ) ) + ; ; 1 0 2 )')))

STMTS10 = {'t10stk': ST_NUMS}
ORDER10 = ['t10stk']
for _n in PREDS10:
    STMTS10['tmi%su' % _n] = unfold_stmt(FRAGS[_n])
    ORDER10.append('tmi%su' % _n)
HEADS10 = [('tmis2fb', TREE_S2F, CONCL_S2F), ('tmiscfb', TREE_SCF, CONCL_SCF),
           ('tmistdb', TREE_STD, CONCL_STD), ('tmidofb', TREE_DOF, CONCL_DOF), ('tmisgfb', TREE_SGF, CONCL_SGF),
           ('tmidnb', TREE_DN, CONCL_DN), ('tmiscxb', TREE_SCX, CONCL_SCX), ('tmip5b', TREE_P5, CONCL_P5),
           ('tmikp', TREE_KP, CONCL_KP), ('tmirts', TREE_RTS, CONCL_RTS), ('tmirgf', TREE_RGF, CONCL_RGF),
           ('tmirsv', TREE_RSV, CONCL_RSV), ('tmis2p', TREE_S2P, CONCL_S2P), ('tmis2s', TREE_S2S, CONCL_S2S)]
TREES10 = {}
for _l, _t, _c in HEADS10:
    STMTS10[_l] = '( %s -> %s )' % (cj(_t), _c)
    TREES10[_l] = (_t, _c)
    ORDER10.append(_l)


def allstmts10():
    return [(l, STMTS10[l]) for l in ORDER10 if l in STMTS10]


# ============================================================ the divOut pieces (statements added as built)
FM_, FQ_ = '( F mod G )', '( |_ ` ( F / G ) )'
IFM_ = 'if ( %s = 0 , 1o , (/) )' % FM_
FINV_DOT = 'if ( ( %s = 0 /\\ H =/= 0 ) , 1o , (/) )' % FM_
TREE_DOT = TREE0('dot', DATA_DOF)
D3Q = UP('D', '3', EWg(FQ_, DK(3)))
CONCL_DOTA = TRI(CS('dot'), CLN('( P ` 0 )', NFL(IFM_), D3Q), '( 5 x. ( TMB ` B ) )')
CONCL_DOTB = TRI(CS('dot'), CLN('E', NFL(FINV_DOT), D3Q), '( ( 6 x. ( TMB ` B ) ) + 2 )')


def add_stmt(label, tree, concl, after=None):
    STMTS10[label] = '( %s -> %s )' % (cj(tree), concl)
    TREES10[label] = (tree, concl)
    if label not in ORDER10:
        ORDER10.append(label)


add_stmt('tmidota', TREE_DOT, CONCL_DOTA)
add_stmt('tmidotb', TREE_DOT, CONCL_DOTB)


# ============================================================ proof helpers
def numtree(tree):
    """the internal antecedent: the theorem's tree with the numeral stack facts"""
    return (tree, NUMS)


def finish(w, st, label):
    """qed: the frozen statement from st : ( ( A /\\ NUMS ) -> C ) and ~ t10stk"""
    tree, concl = TREES10[label]
    k = w.s([], 't10stk', ST_NUMS)
    w.qed([k, st], 'mpan2', STMTS10[label])


def nfl_eq(w, ph, v1, v2, eq):
    """( ph -> NFL( v1 ) = NFL( v2 ) ) from eq : ( ph -> v1 = v2 )"""
    s = w.s
    q = s([s([eq], 'eqeq2d', '( %s -> ( ( TMfl ` h ) = %s <-> ( TMfl ` h ) = %s ) )' % (ph, v1, v2))],
          'adantr', '( ( %s /\\ h e. TMSt ) -> ( ( TMfl ` h ) = %s <-> ( TMfl ` h ) = %s ) )' % (ph, v1, v2))
    return s([q], 'rabbidva', '( %s -> %s = %s )' % (ph, NFL(v1), NFL(v2)))


# ------------------------------------------------------------ loads setting a field to (/) (t7_h_iz's lset_val/lset_ty
# handle 1o and if-terms only; the module is read-only)
def lset_val2(w, ph, kw_of, A, nv_or_mem):
    from t7lib import lamval, st_comps, tuple_facts, _transport
    X_of = lambda t: SETF(t, **kw_of(t))
    val = lamval(w, ph, X_of, A, nv_or_mem, closed(w, ph, 'opex', '%s e. _V' % X_of(A)))
    kw = kw_of(A)
    cl = st_comps(w, ph, A, nv_or_mem)
    comps = [kw.get(f, FLD(f, A)) for f in ORDER]
    cls = []
    for f, comp in zip(ORDER, comps):
        if f in kw:
            if comp == '1o':
                cls.append(closed(w, ph, '1oel2o', '1o e. 2o'))
            elif comp == '(/)':
                cls.append(closed(w, ph, '0el2o', '(/) e. 2o') if f != 'cmp' else closed(w, ph, '0elon', '(/) e. On') if False else
                           closed(w, ph, '0el2o', '(/) e. 2o'))
            else:
                e = w.s([w.s([], '1oel2o', '1o e. 2o'), w.s([], '0el2o', '(/) e. 2o')], 'ifcli', '%s e. 2o' % comp)
                cls.append(w.s([e], 'a1i', '( %s -> %s e. 2o )' % (ph, comp)))
        else:
            cls.append(cl[f])
    mem, vals = tuple_facts(w, ph, comps, cls)
    N = '( %s ` %s )' % ('( u e. TMSt |-> %s )' % X_of('u'), A)
    return _transport(w, ph, N, val, mem, vals, comps)


def lset_ty2(w, ph, mk, lam, kw_of):
    from t7lib import st_comps, tuple_facts
    from t7_e_cmp import lamty as _lamty
    X_of = lambda t: SETF(t, **kw_of(t))
    assert lam == '( u e. TMSt |-> %s )' % X_of('u')
    phu = 'u e. TMSt'
    uu = w.s([], 'id', '( %s -> u e. TMSt )' % phu)
    cl = st_comps(w, phu, 'u', uu)
    kw = kw_of('u')
    comps = [kw.get(f, FLD(f, 'u')) for f in ORDER]
    cls = []
    for f, comp in zip(ORDER, comps):
        if f in kw:
            if comp == '1o':
                cls.append(closed(w, phu, '1oel2o', '1o e. 2o'))
            elif comp == '(/)':
                cls.append(closed(w, phu, '0el2o', '(/) e. 2o'))
            else:
                e = w.s([w.s([], '1oel2o', '1o e. 2o'), w.s([], '0el2o', '(/) e. 2o')], 'ifcli', '%s e. 2o' % comp)
                cls.append(w.s([e], 'a1i', '( %s -> %s e. 2o )' % (phu, comp)))
        else:
            cls.append(cl[f])
    mem, _ = tuple_facts(w, phu, comps, cls)
    sv = w.s([w.s([], 'tmstfi', 'TMSt e. Fin')], 'elexi', 'TMSt e. _V')
    t = _lamty(w, ph, mk, lam, X_of, 'TMSt', sv, mem)
    e = w.s([mk['seq']], 'eqcomd', '( %s -> TMSt = ( 2nd ` T ) )' % ph)
    e2 = w.s([e], 'oveq1d', '( %s -> ( TMSt ^m ( 2nd ` T ) ) = ( ( 2nd ` T ) ^m ( 2nd ` T ) ) )' % ph)
    return w.s([t, e2], 'eleqtrd', '( %s -> %s e. ( ( 2nd ` T ) ^m ( 2nd ` T ) ) )' % (ph, lam))
